### ISSUE TITLE
Recintos abiertos

### ISSUE THREAD

**Issue by pablohevia** [chapulincatastral/generador-gml#1]
Hola,
Creo que hay un pequeño error: los recintos quedan abiertos. En la lista de pares de coordenadas generados, el primer y último par no coinciden.

**Comment by pablohevia** [comment]
Por cierto, la idea es estupenda, ahorra muchísimo trabajo.

**Comment by chapulincatastral** [comment]
Hola pablohevia. El error de los recintos abiertos puede deberse a que, una vez descargada la parcela, debemos utilizar el comando POLCONT para asegurarnos de que, efectivamente, está cerrada.

**Comment by pablohevia** [comment]
Vaya, acabo de probar otra vez, cerrando la polilínea con POLCONT, pero sigue sin funcionarme. ¿Estaré haciendo mal algo?

**Comment by chapulincatastral** [comment]
¿Podrías hacer la Validación Gráfica Alternativa?. En caso de que fuera positiva es que está todo correcto.

**Comment by chapulincatastral** [comment]
Hola. Disculpa, no entendíamos lo que nos querías decir. Pensábamos que es que estabas viendo el .gml  y no te gustaba. En ningún momento mencionaste que era un error en Sede Electrónica del Catastro (SEC).
Al parecer han cambiado los criterios de la validación y efectivamente da un error en validación en la SEC.
Hemos subido una nueva versión que corrige el problema.
Muchas gracias por tu aporte y disculpa el mal entendido.
