### ISSUE TITLE
Catastro no valida GML si el nombre de la parcela tiene espacios

### ISSUE THREAD

**Issue by jagarciavi** [chapulincatastral/generador-gml#2]
Por ejemplo, si la etiqueta de la parcela es una referencia catastral (_49xxxxxxxxxx_) sin espacios no da problemas, pero si la etiqueta es un texto del tipo _Parcela 5605_ no da Catastro por bueno el GML.

**Comment by chapulincatastral** [comment]
Hola. Me parece una buena idea. Si he entendido bien , propones poner un filtro para evitar que el nombre de la parcela contenga espacios.

**Comment by jagarciavi** [comment]
A eso me referia. Un saludo.

**Comment by chapulincatastral** [comment]
Ok. Esta tarde subimos una nueva versión.
Saludos

**Comment by chapulincatastral** [comment]
hecho
